# Generated by Django 3.1.4 on 2021-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('회사명', models.TextField(blank=True, null=True)),
                ('종목코드', models.IntegerField(blank=True, null=True)),
                ('업종', models.TextField(blank=True, null=True)),
                ('주요제품', models.TextField(blank=True, null=True)),
                ('상장일', models.TextField(blank=True, null=True)),
                ('결산월', models.TextField(blank=True, null=True)),
                ('대표자명', models.TextField(blank=True, null=True)),
                ('홈페이지', models.TextField(blank=True, null=True)),
                ('지역', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
